### PR TITLE
End of Quarter Update

### PR DESCRIPTION
**Pull request by xiexr151e**
So far, we have attempted to establish a database implementation on the program.
Documentation is also updated.

### CODE REVIEW

**Comment by agoetz** [comment]
Tests don't work. They only appear to pass because the shell script ``run_test.sh`` that runs a test and is called by Travis CI returns the return value of ``ndiff`` and unfortunately ``ndiff`` returns 0 if a file is not present instead of returning a non-zero error code. 

```
$> cd potential_fitting/qm_mb_energy_calulator/tests/trimer
$> ./run_test.sh 
Traceback (most recent call last):
  File "../../src/driver.py", line 140, in <module>
    molecules = xyz_to_molecules(f)
TypeError: xyz_to_molecules() missing 1 required positional argument: 'config'
first file is short
first file is short
first file is short
```

It looks like ``driver.py`` was not updated to match changes in ``molecule_parser.py``. The tests have also not been updated, I believe we need changes to ``settings.ini``.

**Comment by agoetz** [comment]
Tests still not working.

I merged Ethan's pr 62, which I think duplicated this pr - minus your attempt at fixing the driver.

**Comment by EthanBullVulpe** [comment]
You are correct I forgot to update driver.py. This is because I thought it would be depricated since we are moving to a database format. If not, I'll update it when I get a chance

**Comment by agoetz** [comment]
It may still be useful, even if we have a fully functional database implementation, to be able to use a driver to get many-body energies for a few coordinates manually. At present it also serves the purpose of regression tests. The many-body energies as computed by this driver are correct, which I verified manually. Until we have other tests we should keep these. Thanks.

**Comment by agoetz** [comment]
Closing this pull request as all changes have been incorporated into pr #62

**Pull request closed without merging**
